[package]
name = "neuraledge-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
num-traits = "0.2.19"
rand = "0.8.5"
rayon = "1.10.0"
serde = "1.0.200"
serde_json = "1.0.116"
wgpu = "0.20.0"

